<?php
/**
 * @file
 * Code for the ESN Events Facebook integration.
 */


/**
 * Implementation of hook_ctools_plugin_api().
 */
function satellite_events_facebook_ctools_plugin_api($owner, $api) {
  if ($owner == 'satellite_events_facebook' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function satellite_events_facebook_feeds_plugins() {
  $info = array();
  $info['SatelliteFacebookEventsParser'] = array(
    'name' => 'ESN Satellite Facebook Events parser',
    'description' => 'Parse Facebook event feeds to be mapped to Event nodes of Satellite 4.x.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'SatelliteFacebookEventsParser',
      'file' => 'inc/SatelliteFacebookEventsParser.inc',
      'path' => drupal_get_path('module', 'satellite_events_facebook'),
    ),
  );
  return $info;
}
